# Generated by Django 4.2.7 on 2023-12-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiSenseWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('sdg_index_score', models.FloatField()),
                ('goal_1_score', models.FloatField()),
                ('goal_2_score', models.FloatField()),
                ('goal_3_score', models.FloatField()),
                ('goal_4_score', models.FloatField()),
                ('goal_5_score', models.FloatField()),
                ('goal_6_score', models.FloatField()),
                ('goal_7_score', models.FloatField()),
                ('goal_8_score', models.FloatField()),
                ('goal_9_score', models.FloatField()),
                ('goal_10_score', models.FloatField()),
                ('goal_11_score', models.FloatField()),
                ('goal_12_score', models.FloatField()),
                ('goal_13_score', models.FloatField()),
                ('goal_14_score', models.FloatField()),
                ('goal_15_score', models.FloatField()),
                ('goal_16_score', models.FloatField()),
                ('goal_17_score', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
