# Generated by Django 4.2.7 on 2023-12-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiSenseWeb', '0002_sdg_vehicle_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_number', models.CharField(max_length=255)),
                ('goal_name', models.CharField(max_length=255)),
                ('goal_description', models.CharField(max_length=255)),
            ],
        ),
    ]
