# Generated by Django 4.2.7 on 2023-12-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiSenseWeb', '0003_goals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_country_code', models.CharField(max_length=5)),
                ('country_country_name', models.CharField(max_length=255)),
                ('country_description', models.CharField(max_length=255)),
            ],
        ),
    ]
